#ifndef ERRORS_H
#define ERRORS_H

typedef enum {
    MACRO_NAME_IS_AN_INSTRUCTION = 1,
    DECLARATION_OF_MACRO_LINE_INCLUDES_EXTERNAL_CHARACTERS,
    END_OF_MACRO_LINE_INCLUDES_EXTERNAL_CHARACTERS,
    MACRO_NAME_IS_MISSING,
    ILLEGAL_MACRO_NAME,
    FAILURE_IN_ADDING_MACRO_TO_TABLE,
    LINE_LONGER_THAN_80_CHARACTERS,
    EXTERNAL_COMMA,
    MISSING_COMMA,
    COMMA_NOT_IN_PLACE,
    SAME_DECLARATION_FOR_BOTH_ENTRY_AND_EXTERNAL_SYMBOL,
    ILLEGAL_SYMBOL_NAME,
    SYMBOL_NAME_LONGER_THAN_31_CHARACTERS,
    COLONS_NOT_ADJACENT_TO_SYMBOL,
    SYMBOL_ALREADY_DEFINED,
    DECLARATION_BOTH_FOR_MACRO_AND_SYMBOL,
    SYMBOL_NOT_DEFINED,
    SYMBOL_IS_MISSING,
    ILLEGAL_NUMBER,
    ILLEGAL_ARGUMENT,
    UNKNOWN_INSTRUCTION,
    UNKNOWN_DIRECTIVE,
    UNKNOWN_REGISTER,
    TOO_MANY_ARGUMENTS,
    NOT_ENOUGH_ARGUMENTS,
    OPERAND_NOT_SUITABLE_FOR_INSTRUCTION,
    LABEL_BEFORE_EXTERN_IS_NOT_ALLOWED,
    LABEL_BEFORE_ENTRY_IS_NOT_ALLOWED,
    INVALID_LABEL_IN_RELATIVE_OPERAND,
    INVALID_LABEL_IN_DIRECT_OPERAND,
    MISSING_OPENING_QUOTE,
    MISSING_CLOSING_QUOTE,
    EXTERNAL_CHARACTERS,
    FAILED_TO_EMIT_CODE_WORD_AT_ADDRESS,
    FAILED_TO_EMIT_OPERAND_AT_ADDRESS,
    THIS_INSTRUCTION_TAKES_NO_OPERANDS,
    MISSING_OPERAND,
    MISSING_SOURCE_OPERAND,
    MISSING_DESTINATION_OPERAND,
    ILLEGAL_ADDRESSING_MODE,
    FAILURE_IN_ADDING_SYMBOL_TO_TABLE,
    PARSE_ERROR,
    FAILURE_IN_ADDING_FIXUP_TO_TABLE,
    PROGRAM_TOO_LARGE_AFTER_PASS1,
    PROGRAM_TOO_LARGE,
    INVALID_ARGUMENTS_FOR_PASS1,
    CANNOT_OPEN_FILE,
    READLINE_FAILED_WHILE_READING,
    CODEIMAGE_OUT_OF_RANGE,
    DATAIMAGE_OVERFLOW,
    ERR_MAX
} ErrorCodes;

/**
 * printing error and its line using error code
 * @param errorCode - the enum error code
 * @param lineNumber- the line of the error
 **/
void print_error(unsigned int errorCode, unsigned int lineNumber);

/**
 * printing error without line number
 * @param errorCode - the enum error code
 **/
void print_error_no_line(unsigned int errorCode);

#endif