typedef enum {
    MACRO_NAME_IS_AN_INSTRUCTION = 1,
    DECLERATION_OF_MACRO_LINE_INCLUDES_EXTERNAL_CHARACTERS,
    END_OF_MACRO_LINE_INCLUDES_EXTERNAL_CHARACTERS,
    MACRO_NAME_IS_MISSING,
    ILLEGAL_MACRO_NAME,
    FAILURE_IN_ADDING_MACRO_TO_TABLE,
    LINE_LONGER_THAN_80_CHARACTERS,
    EXTERNAL_COMMA,
    MISSING_COMMA,
    COMMA_NOT_IN_PLACE,
    SAME_DECLERATION_FOR_BOTH_ENTRY_AND_EXTERNAL_SYMBOL,
    ILLEGAL_SYMBOL_NAME,
    SYMBOL_NAME_LONGER_THAN_31_CHARACTERS,
    COLONS_NOT_ADJACEN_TO_SYMBOL,
    SYMBOL_ALREADY_DEFINED,
    DECLERATION_BOTH_FOR_MACRO_AND_SYMBOL,
    SYMBOL_NOT_DEFINED,
    SYMBOL_IS_MISSING,
    ILLEGAL_NUMBER,
    ILLEGAL_ARGUMENT,
    UNKOWN_INSTRUCTION,
    UNKOWN_DIRECTIVE,
    UNKNOWN_REGISTER,
    TOO_MANY_ARGUMENTS,
    NOT_ENOUGH_ARGUMENTS,
    OPERAND_NOT_SUITABLE_FOR_INSTRUCTION,
    LABLE_BEFORE_EXTERN_IS_NOT_ALLOWED,
    LABLE_BEFORE_ENTRY_IS_NOT_ALLOWED,
    INVALID_LABLE_IN_RELATIVE_OPERAND,
    INVALID_LABLE_IN_DIRECT_OPERAND,
    MISSING_OPENING_QUOTE,
    MISSING_CLOSING_QUOTE,
    EXTERNAL_CHARACTERS,
    FAILED_TO_EMIT_CODE_WORD_AT_ADDRESS,
    FAILED_TO_EMIT_OPERAND_AT_ADDRESS,
    THIS_INSTRUCTION_TAKES_NO_OPERANDS,
    MISSING_OPERAND,
    MISSING_SOURCE_OPERAND,
    MISSING_DESTINATION_OPERAND,
    ILLEGAL_ADDERSSING_MODE,
    FAILURE_IN_ADDING_SYMBOL_TO_TABLE,
    PARSE_ERROR,
    ERR_MAX
} ErrorCodes;

/**
 * printing error and its line using error code
 * @param errorCode - the enum error code
 * @param lineNumber- the line of the error
 * @return line number of the error and prints the relevant error
 **/
unsigned int print_error(unsigned int errorCode, unsigned int lineNumber);